// Code generated by command: go run addslice_amd64.go -out addslice_amd64.s -stubs addslice_stub.go. DO NOT EDIT.

package asm

// AddSlice adds corresponding elements of a and b into dst.
func AddSlice(dst []uint64, a []uint64, b []uint64)
