// Code generated by command: go run addslice_amd64.go -out addslice_amd64.s -stubs addslice_stub.go. DO NOT EDIT.

#include "textflag.h"

// func AddSlice(dst []uint64, a []uint64, b []uint64)
// Requires: AVX, AVX2
TEXT ·AddSlice(SB), NOSPLIT, $0-72
	MOVQ dst_base+0(FP), AX
	MOVQ a_base+24(FP), CX
	MOVQ b_base+48(FP), DX
	MOVQ a_len+32(FP), BX
	MOVQ BX, SI
	SHRQ $0x02, SI
	ANDQ $0x03, BX
	CMPQ SI, $0x00
	JE   tail

loop:
	VMOVDQU (CX), Y0
	VPADDQ  (DX), Y0, Y0
	VMOVDQU Y0, (AX)
	ADDQ    $0x20, CX
	ADDQ    $0x20, DX
	ADDQ    $0x20, AX
	DECQ    SI
	JNZ     loop

tail:
	MOVQ BX, SI
	CMPQ SI, $0x00
	JE   done

loop_tail:
	MOVQ (CX), BX
	ADDQ (DX), BX
	MOVQ BX, (AX)
	ADDQ $0x08, CX
	ADDQ $0x08, DX
	ADDQ $0x08, AX
	DECQ SI
	JNZ  loop_tail

done:
	VZEROUPPER
	RET
